#!/usr/bin/env python3
"""Render the onclave runtime .env from Bitwarden Secrets Manager without printing values."""

from __future__ import annotations

import argparse
import json
import os
import stat
import subprocess
import sys
import tempfile
from pathlib import Path

REQUIRED_KEYS = [
    "RABBITMQ_DEFAULT_USER",
    "RABBITMQ_DEFAULT_PASS",
]
OPTIONAL_KEYS = [
    "ONCLAVE_QUEUE_TTL_MS",
    "ONCLAVE_QUEUE_MAX_LENGTH",
    "ONCLAVE_HEARTBEAT_STALE_MS",
    "ONCLAVE_MAX_EXCHANGES",
    "ONCLAVE_MAX_TOTAL_TOKENS",
]
PLACEHOLDERS = {"changeme", "replace_me", "<replace>", "todo", "example"}
SECRET_KEY_SUFFIXES = ("PASSWORD", "PASS", "SECRET", "TOKEN")


def server_url(api_server: str) -> str:
    trimmed = api_server.rstrip("/")
    if trimmed.endswith("/api"):
        trimmed = trimmed[: -len("/api")]
    return trimmed


def fetch_bws(args: argparse.Namespace) -> dict[str, str]:
    token = args.access_token or os.environ.get("BITWARDEN_ACCESS_KEY", "")
    if not token:
        raise RuntimeError("Bitwarden access token is missing; set BITWARDEN_ACCESS_KEY")
    env = dict(os.environ)
    env["BWS_ACCESS_TOKEN"] = token
    api_server = args.api_server or os.environ.get("BITWARDEN_API_SERVER", "")
    if api_server:
        env["BWS_SERVER_URL"] = server_url(api_server)
    command = ["bws", "secret", "list", "--output", "json"]
    if args.project_id:
        command.insert(3, args.project_id)
    result = subprocess.run(command, env=env, capture_output=True, text=True, timeout=60)
    if result.returncode != 0:
        raise RuntimeError("bws secret list failed; verify access token and server URL")
    payload = json.loads(result.stdout or "[]")
    if not isinstance(payload, list):
        raise ValueError("unsupported bws secrets JSON format")
    values: dict[str, str] = {}
    for item in payload:
        if isinstance(item, dict) and "key" in item and "value" in item:
            values[str(item["key"])] = str(item["value"])
    return values


def load_secrets(args: argparse.Namespace) -> dict[str, str]:
    if args.secrets_json:
        raw = json.loads(Path(args.secrets_json).read_text(encoding="utf-8"))
        if isinstance(raw, dict):
            return {str(k): str(v) for k, v in raw.items()}
        raise ValueError("secrets JSON fallback must be an object")
    return fetch_bws(args)


def validate(values: dict[str, str]) -> list[str]:
    errors = []
    for key in REQUIRED_KEYS:
        value = values.get(key, "")
        lowered = value.strip().lower()
        if not value.strip():
            errors.append(f"{key}: missing or empty")
        elif lowered in PLACEHOLDERS or "<replace" in lowered or "changeme" in lowered:
            errors.append(f"{key}: placeholder value rejected")
        elif key.endswith(SECRET_KEY_SUFFIXES) and len(value) < 12:
            errors.append(f"{key}: value is too short")
    return errors


def render(values: dict[str, str]) -> str:
    keys = REQUIRED_KEYS + [key for key in OPTIONAL_KEYS if key in values]
    lines = [
        "# Generated by scripts/onclave-bws-env.py from Bitwarden Secrets Manager",
        "# Do not edit manually",
    ]
    for key in keys:
        lines.append(f"{key}={values.get(key, '')}")
    return "\n".join(lines) + "\n"


def write_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=f".{path.name}.", dir=str(path.parent), text=True)
    tmp_path = Path(tmp)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
        os.chmod(tmp_path, stat.S_IRUSR | stat.S_IWUSR)
        os.replace(tmp_path, path)
        os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)
    finally:
        if tmp_path.exists():
            tmp_path.unlink()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-id", default=os.environ.get("ONCLAVE_BWS_PROJECT_ID", ""))
    parser.add_argument("--api-server")
    parser.add_argument("--access-token")
    parser.add_argument("--secrets-json")
    parser.add_argument("--out")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--validate", action="store_true")
    mode.add_argument("--write", action="store_true")
    return parser


def run(args: argparse.Namespace) -> int:
    values = load_secrets(args)
    errors = validate(values)
    if errors:
        for error in errors:
            print(f"ERROR {error}", file=sys.stderr)
        return 1
    if args.write:
        if not args.out:
            print("ERROR --out is required with --write", file=sys.stderr)
            return 1
        write_atomic(Path(args.out), render(values))
        print(f"Rendered onclave environment with {len(REQUIRED_KEYS)} required keys to {args.out}")
    else:
        print(f"Validated onclave environment with {len(REQUIRED_KEYS)} required keys")
    return 0


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        return run(args)
    except Exception as exc:  # noqa: BLE001 - CLI must redact operational failures.
        print(f"ERROR {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
