#!/usr/bin/env python3
"""Render stack runtime environments from Bitwarden without printing values."""

from __future__ import annotations

import argparse
import json
import os
import stat
import subprocess
import sys
import tempfile
from pathlib import Path

STACKS = {
    "onclave": {
        "required": [
            "RABBITMQ_DEFAULT_USER",
            "RABBITMQ_DEFAULT_PASS",
        ],
        "optional": [
            "ONCLAVE_QUEUE_TTL_MS",
            "ONCLAVE_QUEUE_MAX_LENGTH",
            "ONCLAVE_HEARTBEAT_STALE_MS",
            "ONCLAVE_MAX_EXCHANGES",
            "ONCLAVE_MAX_TOTAL_TOKENS",
        ],
        "defaults": {},
        "aliases": {},
    },
    "menos": {
        "required": [
            "SURREALDB_PASSWORD",
            "S3_ACCESS_KEY",
            "S3_SECRET_KEY",
            "SEARXNG_SECRET",
            "WEBSHARE_PROXY_USERNAME",
            "WEBSHARE_PROXY_PASSWORD",
            "YOUTUBE_API_KEY",
            "OPENROUTER_API_KEY",
            "ANTHROPIC_API_KEY",
        ],
        "optional": [
            "OPENAI_API_KEY",
            "CALLBACK_SECRET",
            "SEMANTIC_SCHOLAR_API_KEY",
        ],
        "defaults": {
            "API_BASE_URL": "http://192.168.16.241:8000",
            "DATA_PATH": "/apps/menos/data",
            "SURREALDB_URL": "ws://192.168.16.241:8080",
            "SURREALDB_USER": "root",
            "SURREALDB_NAMESPACE": "menos",
            "SURREALDB_DATABASE": "menos",
            "S3_BUCKET": "menos",
            "S3_REGION": "us-east-1",
            "MINIO_URL": "192.168.16.241:9000",
            "OLLAMA_URL": "http://192.168.16.241:11434",
        },
        "aliases": {
            "MINIO_ACCESS_KEY": "S3_ACCESS_KEY",
            "MINIO_SECRET_KEY": "S3_SECRET_KEY",
            "MINIO_BUCKET": "S3_BUCKET",
        },
    },
}
PLACEHOLDERS = {"changeme", "replace_me", "<replace>", "todo", "example"}
SECRET_KEY_SUFFIXES = ("PASSWORD", "PASS", "SECRET", "TOKEN", "API_KEY")


def server_url(api_server: str) -> str:
    trimmed = api_server.rstrip("/")
    if trimmed.endswith("/api"):
        trimmed = trimmed[: -len("/api")]
    return trimmed


def fetch_bws(args: argparse.Namespace, project_id: str) -> dict[str, str]:
    token = args.access_token or os.environ.get("BITWARDEN_ACCESS_KEY", "")
    if not token:
        raise RuntimeError("Bitwarden access token is missing; set BITWARDEN_ACCESS_KEY")
    env = dict(os.environ)
    env["BWS_ACCESS_TOKEN"] = token
    api_server = args.api_server or os.environ.get("BITWARDEN_API_SERVER", "")
    if api_server:
        env["BWS_SERVER_URL"] = server_url(api_server)
    command = ["bws", "secret", "list", "--output", "json"]
    if project_id:
        command.insert(3, project_id)
    result = subprocess.run(command, env=env, capture_output=True, text=True, timeout=60)
    if result.returncode != 0:
        raise RuntimeError("bws secret list failed; verify access token and server URL")
    payload = json.loads(result.stdout or "[]")
    if not isinstance(payload, list):
        raise ValueError("unsupported bws secrets JSON format")
    values: dict[str, str] = {}
    for item in payload:
        if isinstance(item, dict) and "key" in item and "value" in item:
            values[str(item["key"])] = str(item["value"])
    return values


def load_secrets(args: argparse.Namespace, project_id: str) -> dict[str, str]:
    if args.secrets_json:
        raw = json.loads(Path(args.secrets_json).read_text(encoding="utf-8"))
        if isinstance(raw, dict):
            return {str(k): str(v) for k, v in raw.items()}
        raise ValueError("secrets JSON fallback must be an object")
    return fetch_bws(args, project_id)


def validate(values: dict[str, str], required_keys: list[str]) -> list[str]:
    errors = []
    for key in required_keys:
        value = values.get(key, "")
        lowered = value.strip().lower()
        if not value.strip():
            errors.append(f"{key}: missing or empty")
        elif lowered in PLACEHOLDERS or "<replace" in lowered or "changeme" in lowered:
            errors.append(f"{key}: placeholder value rejected")
        elif key.endswith(SECRET_KEY_SUFFIXES) and len(value) < 12:
            errors.append(f"{key}: value is too short")
    return errors


def render(
    values: dict[str, str],
    required_keys: list[str],
    optional_keys: list[str],
    defaults: dict[str, str],
    aliases: dict[str, str],
) -> str:
    keys = (
        list(defaults)
        + required_keys
        + [key for key in optional_keys if key in values]
        + list(aliases)
    )
    lines = [
        "# Generated by scripts/onclave-bws-env.py from Bitwarden Secrets Manager",
        "# Do not edit manually",
    ]
    merged = defaults | values
    merged.update({alias: merged[source] for alias, source in aliases.items()})
    for key in keys:
        lines.append(f"{key}={merged.get(key, '')}")
    return "\n".join(lines) + "\n"


def write_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=f".{path.name}.", dir=str(path.parent), text=True)
    tmp_path = Path(tmp)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
        os.chmod(tmp_path, stat.S_IRUSR | stat.S_IWUSR)
        os.replace(tmp_path, path)
        os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)
    finally:
        if tmp_path.exists():
            tmp_path.unlink()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--stack", choices=sorted(STACKS), default="onclave")
    parser.add_argument("--project-id")
    parser.add_argument("--api-server")
    parser.add_argument("--access-token")
    parser.add_argument("--secrets-json")
    parser.add_argument("--out")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--validate", action="store_true")
    mode.add_argument("--write", action="store_true")
    return parser


def run(args: argparse.Namespace) -> int:
    config = STACKS[args.stack]
    project_id = args.project_id or os.environ.get(f"{args.stack.upper()}_BWS_PROJECT_ID", "")
    values = load_secrets(args, project_id)
    required_keys = config["required"]
    optional_keys = config["optional"]
    defaults = config["defaults"]
    aliases = config["aliases"]
    errors = validate(values, required_keys)
    if errors:
        for error in errors:
            print(f"ERROR {error}", file=sys.stderr)
        return 1
    if args.write:
        if not args.out:
            print("ERROR --out is required with --write", file=sys.stderr)
            return 1
        write_atomic(
            Path(args.out), render(values, required_keys, optional_keys, defaults, aliases)
        )
        print(
            f"Rendered {args.stack} environment with {len(required_keys)} required keys "
            f"to {args.out}"
        )
    else:
        print(f"Validated {args.stack} environment with {len(required_keys)} required keys")
    return 0


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        return run(args)
    except Exception as exc:  # noqa: BLE001 - CLI must redact operational failures.
        print(f"ERROR {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
