#!/usr/bin/env python3
"""Render the onclave runtime .env from Infisical without printing secret values."""

from __future__ import annotations

import argparse
import json
import os
import stat
import sys
import tempfile
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

REQUIRED_KEYS = [
    "RABBITMQ_DEFAULT_USER",
    "RABBITMQ_DEFAULT_PASS",
]
OPTIONAL_KEYS = [
    "ONCLAVE_QUEUE_TTL_MS",
    "ONCLAVE_QUEUE_MAX_LENGTH",
    "ONCLAVE_HEARTBEAT_STALE_MS",
    "ONCLAVE_MAX_EXCHANGES",
    "ONCLAVE_MAX_TOTAL_TOKENS",
]
PLACEHOLDERS = {"changeme", "replace_me", "<replace>", "todo", "example"}
SECRET_KEY_SUFFIXES = ("PASSWORD", "PASS", "SECRET", "TOKEN")


def parse_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def normalize_payload(payload: object) -> dict[str, str]:
    if isinstance(payload, dict) and all(isinstance(v, str) for v in payload.values()):
        return {str(k): str(v) for k, v in payload.items()}
    secrets = payload.get("secrets") if isinstance(payload, dict) else payload
    result: dict[str, str] = {}
    if not isinstance(secrets, list):
        raise ValueError("unsupported secrets JSON format")
    for item in secrets:
        if not isinstance(item, dict):
            continue
        key = item.get("secretKey") or item.get("key") or item.get("name")
        value = item.get("secretValue") or item.get("value")
        if key is not None and value is not None:
            result[str(key)] = str(value)
    return result


def fetch_infisical(args: argparse.Namespace) -> dict[str, str]:
    client_id = args.client_id or os.environ.get("INFISICAL_MACHINE_CLIENT_ID")
    client_secret = args.client_secret or os.environ.get("INFISICAL_MACHINE_CLIENT_SECRET")
    if not client_id or not client_secret:
        raise RuntimeError(
            "Infisical machine identity is missing; set vault-backed client id/secret"
        )
    base = args.api_url.rstrip("/")
    login = json.dumps({"clientId": client_id, "clientSecret": client_secret}).encode()
    req = urllib.request.Request(
        f"{base}/api/v1/auth/universal-auth/login",
        data=login,
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=20) as response:
        token = json.loads(response.read().decode()).get("accessToken")
    if not token:
        raise RuntimeError("Infisical auth succeeded without access token")
    query = urllib.parse.urlencode(
        {
            "workspaceId": args.project,
            "environment": args.environment,
            "secretPath": args.path,
            "recursive": "false",
        }
    )
    req = urllib.request.Request(
        f"{base}/api/v3/secrets/raw?{query}",
        headers={"Authorization": f"Bearer {token}"},
    )
    with urllib.request.urlopen(req, timeout=20) as response:
        return normalize_payload(json.loads(response.read().decode()))


def load_secrets(args: argparse.Namespace) -> dict[str, str]:
    if args.secrets_json:
        return normalize_payload(json.loads(Path(args.secrets_json).read_text(encoding="utf-8")))
    try:
        return fetch_infisical(args)
    except urllib.error.URLError as exc:
        raise RuntimeError(
            "Infisical request failed; verify URL, project, environment, path, and machine identity"
        ) from exc


def validate(values: dict[str, str]) -> list[str]:
    errors = []
    for key in REQUIRED_KEYS:
        value = values.get(key, "")
        lowered = value.strip().lower()
        if not value.strip():
            errors.append(f"{key}: missing or empty")
        elif lowered in PLACEHOLDERS or "<replace" in lowered or "changeme" in lowered:
            errors.append(f"{key}: placeholder value rejected")
        elif key.endswith(SECRET_KEY_SUFFIXES) and len(value) < 12:
            errors.append(f"{key}: value is too short")
    return errors


def render(values: dict[str, str]) -> str:
    keys = REQUIRED_KEYS + [key for key in OPTIONAL_KEYS if key in values]
    lines = [
        "# Generated by scripts/onclave-infisical-env.py from Infisical",
        "# Do not edit manually",
    ]
    for key in keys:
        lines.append(f"{key}={values.get(key, '')}")
    return "\n".join(lines) + "\n"


def write_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=f".{path.name}.", dir=str(path.parent), text=True)
    tmp_path = Path(tmp)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
        os.chmod(tmp_path, stat.S_IRUSR | stat.S_IWUSR)
        os.replace(tmp_path, path)
        os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)
    finally:
        if tmp_path.exists():
            tmp_path.unlink()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project", default=os.environ.get("ONCLAVE_INFISICAL_PROJECT", ""))
    parser.add_argument(
        "--environment", default=os.environ.get("ONCLAVE_INFISICAL_ENVIRONMENT", "")
    )
    parser.add_argument("--path", default=os.environ.get("ONCLAVE_INFISICAL_PATH", "/onclave"))
    parser.add_argument(
        "--api-url", default=os.environ.get("INFISICAL_API_URL", "https://infisical.ilude.com")
    )
    parser.add_argument("--client-id")
    parser.add_argument("--client-secret")
    parser.add_argument("--template", default="")
    parser.add_argument("--secrets-json")
    parser.add_argument("--out")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--validate", action="store_true")
    mode.add_argument("--write", action="store_true")
    return parser


def run(args: argparse.Namespace) -> int:
    template = parse_env_file(Path(args.template)) if args.template else {}
    values = {**template, **load_secrets(args)}
    errors = validate(values)
    if errors:
        for error in errors:
            print(f"ERROR {error}", file=sys.stderr)
        return 1
    if args.write:
        if not args.out:
            print("ERROR --out is required with --write", file=sys.stderr)
            return 1
        write_atomic(Path(args.out), render(values))
        print(f"Rendered onclave environment with {len(REQUIRED_KEYS)} required keys to {args.out}")
    else:
        print(f"Validated onclave Infisical environment with {len(REQUIRED_KEYS)} required keys")
    return 0


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        return run(args)
    except Exception as exc:  # noqa: BLE001 - CLI must redact operational failures.
        print(f"ERROR {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
